# Generated by Django 6.0.2 on 2026-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
