# Generated by Django 6.0.3 on 2026-03-12 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_pelicula_genero_alter_pelicula_puntuacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Director', 'verbose_name_plural': 'Directores'},
        ),
        migrations.AlterModelOptions(
            name='genero',
            options={'ordering': ['nombre'], 'verbose_name': 'Género', 'verbose_name_plural': 'Géneros'},
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['-fecha_estreno'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
    ]
